### ISSUE TITLE
Currently broken?

### ISSUE THREAD

**Issue by wulfsolter** [ClientMyAdmin/clientmyadmin.github.io#1]
Just tried installing on latest Chrome Canary. Extension won't load...

<img width="1272" alt="screen shot 2016-02-11 at 1 43 59 pm" src="https://cloud.githubusercontent.com/assets/1692132/12966702/a3162c38-d0c5-11e5-9631-8bde8fc628cf.png">

**Comment by jimmywarting** [comment]
I made a hotfix, changed some resources, works for the moment but needs to be fixed.
Thanks for notifying me!

**Comment by wulfsolter** [comment]
Works now! Looks really nice man! Really nice!!! Hope so submit some PRs soon :)

**Comment by jimmywarting** [comment]
I have it as a [bookmarklet](clientmyadmin.github.io). So it is possible to use it on IE, firefox, safari and mobile devices as well. This chrome extension just simple use that bookmarklet.

I could put up the source for this aswell (not just the minified version) in this repo

**Comment by wulfsolter** [comment]
Yep, loving the bookmarklet functionality :) Makes it _really_ easy to use!

**Comment by jimmywarting** [comment]
The idéa with the bookmarklet was the you would just simple create a `/www/clientmyadmin.html` with just this code:

```
Loading...
<script src='https://clientmyadmin.github.io/javascripts/latest/bookmarklet.js'></script>
```

And be able to access it from all browsers

I have uploaded the all the source now: https://github.com/ClientMyAdmin
